### ISSUE TITLE
Implement Webhook Headers

### ISSUE THREAD

**Issue by ConradKurth** [stumpylog/gotenberg-client#6]
Hello!
It seems like the extra headers is not working on the version 7. It has been updated to 

Gotenberg-Webhook-Extra-Http-Headers

Should add support for those as well as the other pre defined headers on a route basis.

I might be getting to this soonish? (maybe a couple weeks) but raising it here if someone gets to it first :)

**Comment by stumpylog** [comment]
I don't find that header value mentioned in the routes documentation?

**Comment by stumpylog** [comment]
If you're referring to the Custom HTTP Headers for all Chromium routes (https://gotenberg.dev/docs/routes#custom-http-headers), that is implemented for that route as the `.headers` method.

Nothing about the webhook headers is implemented at this time.  I only needed the routes.  It's just HTTP headers, so that easy enough to add

**Comment by ConradKurth** [comment]
Ohhhhh got it, i miss understood! Yes you are correct. Sounds good, I will hopefully be able to get to this for you in a week or so! Thanks for the clarity here

**Comment by stumpylog** [comment]
Let me know if you still plan to implement this feature, otherwise I may get to it this week.

**Comment by ConradKurth** [comment]
@stumpylog Take a crack at it! I actually wont be able to get to this for a little bit longer than I thought

**Comment by stumpylog** [comment]
0.5.0 is in the process of releasing.  It provides simplified setting of the 4 webhook headers
